import Head from 'next/head'
import Navbar from '@components/Navbar';
import Code from '@components/Code';

const linkClassName = "text-sky-500 hover:text-sky-600 transition-all text-sm font-medium block mb-1"

export default function Avatar() {

  return (
    <>
      <Head>
        <title>Avatar Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Avatar Data</h1>

          <div className="my-8 dark:text-white">
            <a href={`${process.env.API_URL}/api/avatars`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/avatars
            </a>
            <a href={`${process.env.API_URL}/api/avatars?id=1`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/avatars?id=1
            </a>
            <a href={`${process.env.API_URL}/api/avatars/1`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/avatars/1
            </a>
          </div>

          <Code name={`Response From /api/avatars`} code={`[
  {
    "id": 1,
    "picture": "https://ui-avatars.com/api/?name=Kathy+Howard&color=ef4444&background=eef2ff&bold=true&rounded=true",
    "name": "Kathy Howard"
  },
  {
    "id": 2,
    "picture": "https://ui-avatars.com/api/?name=Banks+Jimenez&color=f97316&background=eef2ff&bold=true&rounded=true",
    "name": "Banks Jimenez"
  },
]`} />

          <Code name="Response From /api/avatars/1" code={`{
  "id": 1,
  "picture": "https://ui-avatars.com/api/?name=Kathy+Howard&color=ef4444&background=eef2ff&bold=true&rounded=true",
  "name": "Kathy Howard"
}`} />

          <Code name="pages/api/avatars" code={`import { avatars } from "@data/avatars"

export default function handler(req, res) {
  const { id } = req.query
  if (id !== undefined) {
    const filtered = avatars.filter(avatar => avatar.id == id)
    if (filtered.length > 0) {
      res.status(200).send(JSON.stringify(filtered[0], null, 2));
      // res.status(200).json(filtered[0])
    }
    else {
      res.status(404).json({ id: id, error: "Not Found" })
    }
  }
  else {
    // res.setHeader('Content-Type', 'application/json')
    res.status(200).send(JSON.stringify(avatars, null, 2));
    // res.status(200).json(avatars)
  }
}`} />

          <Code name="pages/api/avatars/[id]" code={`import { avatars } from "@data/avatars"

export default function handler(req, res) {

  const { id } = req.query
  const filtered = avatars.filter(avatar => avatar.id == id)

  if (filtered.length > 0) {
    res.status(200).send(JSON.stringify(filtered[0], null, 2));
    // res.status(200).json(filtered[0])
  }
  else {
    res.status(404).json({ id: id, error: "Not Found" })
  }
}`} />

        </div>
      </main >
    </>
  )
}
