import Head from 'next/head'
import Navbar from '@components/Navbar';
import Code from '@components/Code';

const linkClassName = "text-sky-500 hover:text-sky-600 transition-all text-sm font-medium block mb-1"

export default function Customer() {

  return (
    <>
      <Head>
        <title>Customer Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold">Customer Data</h1>

          <div className="my-8 dark:text-white">
            <a href={`${process.env.API_URL}/api/customers`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/customers
            </a>
            <a href={`${process.env.API_URL}/api/customers?id=1`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/customers?id=1
            </a>
            <a href={`${process.env.API_URL}/api/customers/1`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/customers/1
            </a>
          </div>

          <Code name={`Response From /api/customers`} code={`[
  {
    "id": 1,
    "picture": "https://ui-avatars.com/api/?name=Kathy+Howard&color=ef4444&background=eef2ff&bold=true&rounded=true",
    "age": 21,
    "name": "Kathy Howard",
    "gender": "female",
    "company": "EXOSIS",
    "email": "kathyhoward@exosis.com",
    "phone": "+1 (920) 583-2342",
    "address": "523 Wolf Place, Kaka, Kansas, 9315"
  },
  {
    "id": 2,
    "picture": "https://ui-avatars.com/api/?name=Banks+Jimenez&color=f97316&background=eef2ff&bold=true&rounded=true",
    "age": 33,
    "name": "Banks Jimenez",
    "gender": "male",
    "company": "STREZZO",
    "email": "banksjimenez@strezzo.com",
    "phone": "+1 (862) 526-2251",
    "address": "305 Sharon Street, Rehrersburg, Hawaii, 8431"
  },
]`} />

          <Code name="Response From /api/customers/1" code={`{
  "id": 1,
  "picture": "https://ui-avatars.com/api/?name=Kathy+Howard&color=ef4444&background=eef2ff&bold=true&rounded=true",
  "age": 21,
  "name": "Kathy Howard",
  "gender": "female",
  "company": "EXOSIS",
  "email": "kathyhoward@exosis.com",
  "phone": "+1 (920) 583-2342",
  "address": "523 Wolf Place, Kaka, Kansas, 9315"
}`} />

          <Code name="pages/api/customers" code={`import { customers } from "@data/customers"

export default function handler(req, res) {
  const { id } = req.query
  if (id !== undefined) {
    const filtered = customers.filter(customer => customer.id == id)
    if (filtered.length > 0) {
      res.status(200).send(JSON.stringify(filtered[0], null, 2));
      // res.status(200).json(filtered[0])
    }
    else {
      res.status(404).json({ id: id, error: "Not Found" })
    }
  }
  else {
    // res.setHeader('Content-Type', 'application/json')
    res.status(200).send(JSON.stringify(customers, null, 2));
    // res.status(200).json(customers)
  }
}`} />

          <Code name="pages/api/customers/[id]" code={`import { customers } from "@data/customers"

export default function handler(req, res) {

  const { id } = req.query
  const filtered = customers.filter(customer => customer.id == id)

  if (filtered.length > 0) {
    res.status(200).send(JSON.stringify(filtered[0], null, 2));
    // res.status(200).json(filtered[0])
  }
  else {
    res.status(404).json({ id: id, error: "Not Found" })
  }
}`} />

        </div>
      </main >
    </>
  )
}
