import Head from 'next/head'
import Navbar from '@components/Navbar';
import Code from '@components/Code';

const linkClassName = "text-sky-500 hover:text-sky-600 transition-all text-sm font-medium block mb-1"

export default function Avatar() {

  return (
    <>
      <Head>
        <title>Hero Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold">Hero Data</h1>

          <div className="my-8 dark:text-white">
            <a href={`${process.env.API_URL}/api/heroes`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/heroes
            </a>
            <a href={`${process.env.API_URL}/api/heroes?name=Abdurrahman%20Baswedan`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/heroes?name=Abdurrahman%20Baswedan
            </a>
            <a href={`${process.env.API_URL}/api/heroes?q=angkatan`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/heroes?q=angkatan
            </a>
            <a href={`${process.env.API_URL}/api/heroes?alive_start=1900&alive_end=1945`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/heroes?alive_start=1900&alive_end=1945
            </a>
            <a href={`${process.env.API_URL}/api/heroes?birth_start=1920&birth_end=1925`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/heroes?birth_start=1920&birth_end=1925
            </a>
            <a href={`${process.env.API_URL}/api/heroes?ascend_start=2000&ascend_end=2005`} className={linkClassName} target="_blank" rel="noreferrer">
              {process.env.API_URL}/api/heroes?ascend_start=2000&ascend_end=2005
            </a>
          </div>

          <Code name={`Response From /api/heroes`} code={`[
  {
    "name": "Abdul Halim Majalengka",
    "birth_year": 1887,
    "death_year": 1962,
    "description": "Aktivis kemerdekaan dan Ulama; Badan Penyelidik Usaha Persiapan Kemerdekaan Indonesia",
    "ascension_year": 2008
  },
  {
    "name": "Abdul Haris Nasution",
    "birth_year": 1918,
    "death_year": 2000,
    "description": "Jenderal Angkatan Darat; dua kali diangkat sebagai Kepala Staf Angkatan Darat",
    "ascension_year": 2002
  },
]`} />

          <Code name={`Response From /api/heroes?name=Abdurrahman%20Baswedan`} code={`[
  {
    "name": "Abdurrahman Baswedan",
    "birth_year": 1908,
    "death_year": 1986,
    "description": "Nasionalis dan mubaligh yang meyakinkan Mesir untuk mengakui kemerdekaan Indonesia secara de facto",
    "ascension_year": 2018
  }

]`} />

          <Code name="pages/api/heroes" code={`import { heroes } from "@data/heroes";

export default function handler(req, res) {
  let result = heroes

  if (req.query['name']) {
    result = heroes.filter((person) => {
      return person.name.toLowerCase().includes(req.query['name'].trim().toLowerCase())
    });
  }

  if (req.query['q']) {
    result = heroes.filter((person) => {
      return (person.name.toLowerCase().includes(req.query['q'].toLowerCase()) || person.description.toLowerCase().includes(req.query['q'].toLowerCase()))
    });
  }

  if (req.query['alive_start'] && req.query['alive_end']) {
    result = heroes.filter((person) => {
      return parseInt(person.birth_year) >= req.query['alive_start'] && parseInt(person.death_year) <= req.query['alive_end']
    });
  }

  if (req.query['birth_start'] && req.query['birth_end']) {
    result = heroes.filter((person) => {
      return parseInt(person.birth_year) >= req.query['birth_start'] && person.birth_year <= req.query['birth_end']
    });
  }

  if (req.query['ascend_start'] && req.query['ascend_end']) {
    result = heroes.filter((person) => {
      return parseInt(person.ascension_year) >= req.query['ascend_start'] && parseInt(person.ascension_year) <= req.query['ascend_end']
    });
  }

  if (result.length == 0) return res.status(200).json({ message: 'Not Found' })
  res.status(200).send(JSON.stringify(result, null, 2));
  // res.status(200).json(heroes);
  return;
}`} />

        </div>
      </main >
    </>
  )
}
